In [1]:
# TOTAL- Complete code
import mysql.connector
from faker import Faker
import random

def execute_sql_file(cursor, sql_file):
    """Execute SQL queries from a file"""
    with open(sql_file, 'r') as f:
        queries = f.read().split(';')

    for query in queries:
        if query.strip():
            cursor.execute(query)

host="localhost"
port='3306'
user="root"
password="qwerty"
database=input('Enter the Database name here:')
                       
            
            
# Connect to MySQL

conn = mysql.connector.connect(
    host=host,
    port=port,
    user=user,
    password=password
      # Change this to your database name
)
cursor = conn.cursor()
# cursor.execute( 'DROP DATABASE IF EXISTS (%s)', (database))
cursor.execute('DROP DATABASE IF EXISTS {}'.format(database))

# cursor.execute( 'CREATE DATABASE  (%s)', (database))
cursor.execute('CREATE DATABASE {}'.format(database))

# cursor.execute( 'USE (%s)', (database))
cursor.execute('USE {}'.format(database))

# Execute SQL file to create tables
execute_sql_file(cursor, r"C:\Users\rkais\OneDrive\Desktop\NC_Assessment\NC_Assessment_SAP_PKFK_RI_Slide_2_3.sql")  # Change the path to your SQL file
execute_sql_file(cursor, r"C:\Users\rkais\OneDrive\Desktop\NC_Assessment\NC_Assessment_SAP_PKFK_RI_Slide_4.sql")  # Change the path to your SQL file
execute_sql_file(cursor, r"C:\Users\rkais\OneDrive\Desktop\NC_Assessment\NC_Assessment_SAP_PKFK_RI_Slide_5.sql")  # Change the path to your SQL file

# Create Faker instance
fake = Faker()



# Generate and insert fake data into BVOR table
for _ in range(10000):
    bukrs = fake.random_number(digits=4)
    belnr = fake.random_number(digits=10)
    gjahr = fake.random_number(digits=4)
    cursor.execute("INSERT INTO BVOR (BUKRS, BELNR, GJAHR) VALUES (%s, %s, %s)", (bukrs, belnr, gjahr))

# Generate and insert fake data into BKPF table
for _ in range(10000):
    bvor_id = random.randint(1, 10000)  # Assuming 10000 records in BVOR table
    cursor.execute("INSERT INTO BKPF (BVOR_ID) VALUES (%s)", (bvor_id,))

# Generate and insert fake data into BSIP table
for _ in range(10000):
    bkpf_id = random.randint(1, 10000)  # Assuming 10000 records in BKPF table
    lifnr = fake.random_number(digits=10)
    waers = fake.currency_code()
    bldat = fake.date(pattern="%Y%m%d")
    wrbtr = fake.random_number(digits=13)
    wrbtr1 = fake.random_number(digits=13)
    buzei = fake.random_number(digits=3)
    cursor.execute("INSERT INTO BSIP (BKPF_ID, LIFNR, WAERS, BLDAT, WRBTR, WRBTR1, BUZEI) VALUES (%s, %s, %s, %s, %s, %s, %s)", (bkpf_id, lifnr, waers, bldat, wrbtr, wrbtr1, buzei))

# Generate and insert fake data into BSEG table
BSEG_IDs=[]
for _ in range(10000):
    bkpf_id = random.randint(1, 10000)  # Assuming 10000 records in BKPF table
    buzei = fake.random_number(digits=3)
    cursor.execute("INSERT INTO BSEG (BKPF_ID, BUZEI) VALUES (%s, %s)", (bkpf_id, buzei))
    BSEG_IDs.append(cursor.lastrowid)

    
# Generate and insert fake data into BSEC, and BSET tables
for table_name in [ 'BSEC', 'BSET']:
    for _ in range(10000):
        bkpf_id = random.randint(1, 10000)
        buzei = fake.random_number(digits=3)
        cursor.execute(f"INSERT INTO {table_name} (BKPF_ID, BUZEI) VALUES (%s, %s)", (bkpf_id, buzei))
    conn.commit()


# Generate and insert fake data into BSAD, BSAK, BSIS, and BSAS tables
for table_name in ['BSAD', 'BSAK', 'BSIS', 'BSAS', 'BSIK','BSID']:
    try:
        for i in BSEG_IDs:
            kunnr = fake.random_number(digits=10)
            lifnr = fake.random_number(digits=10)
            umsks = fake.random_letter()
            umskz = fake.random_letter()
            augdt = fake.date(pattern="%Y%m%d")
            augbl = fake.random_number(digits=10)
            zuonr = fake.random_number(digits=18)
            hkont = fake.random_number(digits=10)
            
            if table_name == 'BSAD' or table_name == 'BSID':
                cursor.execute(f"INSERT INTO {table_name} (BSEG_ID, KUNNR , UMSKS, UMSKZ, AUGDT, AUGBL, ZUONR) VALUES (%s, %s, %s, %s, %s, %s, %s)", (i,kunnr, umsks, umskz, augdt, augbl, zuonr))
            if table_name == 'BSIS' or table_name == 'BSAS':
                cursor.execute(f"INSERT INTO {table_name} (BSEG_ID,HKONT, AUGDT, AUGBL, ZUONR) VALUES (%s, %s, %s, %s, %s)", (i,hkont, augdt, augbl, zuonr))
            if table_name == 'BSIK' or table_name == 'BSAK':
                cursor.execute(f"INSERT INTO {table_name} (BSEG_ID, LIFNR, UMSKS, UMSKZ, AUGDT, AUGBL, ZUONR) VALUES (%s, %s, %s, %s, %s, %s, %s)", (i, lifnr, umsks, umskz, augdt, augbl, zuonr))

    except mysql.connector.Error as err:
        print(f"Error inserting data into table {table_name}: {err}") 
# payr,kfc1,lfc1
  
for _ in range(10000):#PAYR
    zbukr = fake.random_number(digits=4)
    hbkid = fake.random_number(digits=5)
    hktid = fake.random_number(digits=5)
    zlsch = fake.random_number(digits=1)
    checkt = fake.random_number(digits=13)
    cursor.execute("INSERT INTO PAYR (ZBUKR, HBKID, HKTID, ZLSCH, CHECKT) VALUES (%s, %s, %s, %s, %s)", (zbukr, hbkid, hktid, zlsch, checkt))
    
for _ in range(10000): #LFC1
    bukrs = fake.random_number(digits=4)
    lifnr = fake.random_number(digits=10)
    gjahr = fake.random_number(digits=4)
    cursor.execute("INSERT INTO LFC1 (BUKRS, LIFNR, GJAHR) VALUES (%s, %s, %s)", (bukrs, lifnr, gjahr))   
    
    
for _ in range(10000): #KNC1
    bukrs = fake.random_number(digits=4)
    kunnr = fake.random_number(digits=10)
    gjahr = fake.random_number(digits=4)
    cursor.execute("INSERT INTO KNC1 (BUKRS, KUNNR, GJAHR) VALUES (%s, %s, %s)", (bukrs, kunnr, gjahr))
    
    
# ------      

# Generate and insert fake data into LFA1 table
for _ in range(10000):
    lifnr = fake.random_int(min=1000000000, max=9999999999)  # Generating a 10-digit number
    cursor.execute("INSERT INTO LFA1 (LIFNR) VALUES (%s)", (str(lifnr),))

# Generate and insert fake data into LFM1 table
for _ in range(10000):
    lfa1_id = random.randint(1, 10000)  # Assuming 10000 records in LFA1 table
    ekorg = fake.random_number(digits=4)
    cursor.execute("INSERT INTO LFM1 (LFA1_ID, EKORG) VALUES (%s, %s)", (lfa1_id, ekorg))

# Generate and insert fake data into LFM2 table
for _ in range(10000):
    lfm1_id = random.randint(1, 10000)  # Assuming 10000 records in LFM1 table
    ltsnr = fake.random_number(digits=6)
    werks = fake.random_number(digits=4)
    cursor.execute("INSERT INTO LFM2 (LFM1_ID, LTSNR, WERKS) VALUES (%s, %s, %s)", (lfm1_id, ltsnr, werks))

# Generate and insert fake data into LFBK table
for _ in range(10000):
    lfa1_id = random.randint(1, 10000)  # Assuming 10000 records in LFA1 table
    banks = fake.random_number(digits=3)
    bankl = fake.random_number(digits=15)
    bankn = fake.random_number(digits=18)
    cursor.execute("INSERT INTO LFBK (LFA1_ID, BANKS, BANKL, BANKN) VALUES (%s, %s, %s, %s)", (lfa1_id, banks, bankl, bankn))

# Generate and insert fake data into LFB1 table
for _ in range(10000):
    lfa1_id = random.randint(1, 10000)  # Assuming 10000 records in LFA1 table
    bukrs = fake.random_number(digits=4)
    cursor.execute("INSERT INTO LFB1 (LFA1_ID, BUKRS) VALUES (%s, %s)", (lfa1_id, bukrs))

# Generate and insert fake data into LFB5 table
for _ in range(10000):
    lfb1_id = random.randint(1, 10000)  # Assuming 10000 records in LFB1 table
    maber = fake.random_number(digits=2)
    cursor.execute("INSERT INTO LFB5 (LFB1_ID, MABER) VALUES (%s, %s)", (lfb1_id, maber))
 # slide 5 paste

# Generate and insert fake data into KNA1 table
KNA1_IDs=[]

for _ in range(10000):
    KUNNR = fake.random_int(min=1000,max=9999)
    cursor.execute("INSERT INTO KNA1 (KUNNR) VALUES (%s)", (KUNNR,))
    KNA1_IDs.append(cursor.lastrowid)


# Generate and insert fake data into KNVV table
KNVV_IDs=[]
for i in KNA1_IDs:   
    VKORG = fake.random_number(digits=4)
    VTWEG = fake.random_number(digits=2)
    SPART = fake.random_number(digits=2)
    cursor.execute("INSERT INTO KNVV (KNA1_ID,VKORG, VTWEG, SPART) VALUES (%s,%s,%s, %s)", (i,VKORG, VTWEG, SPART))
    KNVV_IDs.append(cursor.lastrowid)

# Generate and insert fake data into KNVP table
for _ in range(10000):
    
    KNVV_ID=random.choice(KNVV_IDs)
    PARVW = fake.random_number(digits=2)
    PARZA = fake.random_number(digits=3)
    cursor.execute("INSERT INTO KNVP (KNVV_ID,PARVW, PARZA) VALUES (%s, %s,%s)", (KNVV_ID,PARVW, PARZA))


# Generate and insert fake data into KNVD table
for _ in range(10000):
    KNVV_ID=random.choice(KNVV_IDs)
    NA_KSCHL = fake.random_number(digits=4)
    SPRAS = fake.random_number(digits=2)
    cursor.execute("INSERT INTO KNVD (KNVV_ID,NA_KSCHL, SPRAS) VALUES (%s,%s, %s)", (KNVV_ID,NA_KSCHL, SPRAS))


# Generate and insert fake data into KNB1 table
KNB1_IDs=[]

for _ in range(10000):
    KNA1_ID=random.choice(KNA1_IDs)
    BUKRS = fake.random_int(min=1000,max=9999)
    cursor.execute("INSERT INTO KNB1 (KNA1_ID,BUKRS) VALUES (%s,%s)", (KNA1_ID,BUKRS))
    KNB1_IDs.append(cursor.lastrowid)

# Generate and insert fake data into KNB5 table

for _ in range(10000):
    KNB1_ID=random.choice(KNB1_IDs)
    MABER = fake.random_number(digits=2)
    cursor.execute("INSERT INTO KNB5 (KNB1_ID,MABER ) VALUES (%s,%s)", (KNB1_ID,MABER))



    
# Commit changes
conn.commit()

# Close connection
cursor.close()
conn.close()

print("Fake data inserted successfully.")

Enter the Database name here:ases
Fake data inserted successfully.

In [2]:
import pandas as pd
conn = mysql.connector.connect(
    host=host,
    port=port,
    user=user,
    password=password,
    database=database
    # Change this to your database name
)


cursor = conn.cursor()
cursor.execute("SELECT * FROM BKPF LIMIT 10")

# Fetching all rows from the result set
result = cursor.fetchall()
column_names = [i[0] for i in cursor.description]

# Creating a DataFrame using pandas
df = pd.DataFrame(result, columns=column_names)
pd.DataFrame(df)
# Displaying the DataFrame
print(df)

   BKPF_ID  BVOR_ID
0     4653        4
1     2357        5
2     4480        5
3     5081        5
4     5915        5
5     4728        7
6     8241        8
7     8412        8
8      638        9
9     1453        9

In [3]:
cursor.execute("DELETE  FROM BVOR WHERE BVOR_ID='9'")

conn.commit()

In [4]:
cursor.execute("SELECT * FROM BKPF LIMIT 10")

# Fetching all rows from the result set
result = cursor.fetchall()
column_names = [i[0] for i in cursor.description]

# Creating a DataFrame using pandas
df = pd.DataFrame(result, columns=column_names)
pd.DataFrame(df)
# Displaying the DataFrame
print(df)

   BKPF_ID  BVOR_ID
0     4653        4
1     2357        5
2     4480        5
3     5081        5
4     5915        5
5     4728        7
6     8241        8
7     8412        8
8     2399       11
9     4709       11

In [5]:
# Closing the cursor and connection
cursor.close()
conn.close()